Add exception type
hmcts/em-ccd-orchestrator pull request #1291
Opened 2023-09-13 15:14 UTC by mdayican

### JIRA link (if applicable) ###
Add custom exception,
IOException is misleading.

2023-09-13 15:34 UTC, yogesh-hullatti requested changes

2023-09-13 15:34 UTC, yogesh-hullatti commented on src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
> +        throw new StitchingTaskMaxRetryException();
Seems this class is missing?

2023-09-13 15:37 UTC, mdayican commented on src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
> +        throw new StitchingTaskMaxRetryException();
added

2023-09-14 07:39 UTC, yogesh-hullatti approved these changes

2023-09-14 07:39 UTC, merged