RIA-8846 Include the existing files from reheard bundle in the remitt…
hmcts/em-ccd-orchestrator pull request #1577
Opened 2024-05-01 08:43 UTC by neha-aggarw

…ed bundle as well

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-01 09:31 UTC, ThomasKKC approved these changes

2024-05-01 09:32 UTC, ThomasKKC requested changes

2024-05-01 09:32 UTC, ThomasKKC commented on src/main/resources/bundleconfiguration/iac-remitted-reheard-hearing-bundle-config.yaml
> +  - name: Decisions and reasons documents
We have 'Decisions and reasons documents' and 'Reheard hearing documents' already?

2024-05-08 08:26 UTC, ThomasKKC approved these changes

2024-05-08 09:32 UTC, mdayican approved these changes

2024-05-08 09:32 UTC, merged